Messages create
Yoshitaka8419/chat-space pull request #6
Opened 2019-01-17 09:32 UTC by Yoshitaka8419

# WHAT
**Chatspaceメッセージ送信機能実装** 
 
# WHY
**メッセージをやりとりする上で必要な機能**

2019-01-17 09:42 UTC, takebn26 requested changes

2019-01-17 09:42 UTC, takebn26 commented on app/assets/javascripts/message.js
> +    // console.log("あああ");
消しましょう

2019-01-17 09:42 UTC, takebn26 commented on app/assets/javascripts/message.js
> +      $('.form__message').val('');
resetメソッド使いましょう

2019-01-17 09:42 UTC, takebn26 commented on app/controllers/messages_controller.rb
> +      @message = @group.message.includes(:user)
render :indexするなら@messagesも必要ですね

2019-01-17 09:42 UTC, takebn26 commented on app/views/messages/create.json.jbuilder
> +json.time    @message.created_at
時間がごにょごにょ出てしまっていると思うので整形しましょう

2019-01-17 09:43 UTC, takebn26 commented
gyazoでgifも貼ってください！

2019-01-19 03:54 UTC, Yoshitaka8419 commented on app/assets/javascripts/message.js
> +    // console.log("あああ");
消しました。

2019-01-19 03:54 UTC, Yoshitaka8419 commented on app/assets/javascripts/message.js
> +      $('.form__message').val('');
document.$('form').reset()

↑resetメソッド追記しました。

2019-01-19 03:54 UTC, Yoshitaka8419 commented on app/views/messages/create.json.jbuilder
> +json.time    @message.created_at
.strftime("%Y/%m/%d %H:%M")

↑追加しました。

https://i.gyazo.com/ce1dcb57e033c5b3620e52be88978f0e.png

↑gyazoでgifも貼りました。

2019-01-19 09:36 UTC, yuki-uchida requested changes

2019-01-19 09:36 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +function scroll() {
scrollだと少しメソッド名が曖昧すぎますね。RailsではJSは全てのページで走るので、他のjsなどに同じ名前が会った時にエラーが起きてしまいます
なので、ここはもう少し具体的に、scrollToNewestMessageのようにしましょう

2019-01-19 09:36 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +    .done(function(data){
受け取ったものがdataだと少しわかりづらいので、new_messagesやnew_messageとしましょう

2019-01-19 10:13 UTC, Yoshitaka8419 commented on app/assets/javascripts/message.js
> +function scroll() {
拝承しました。修正しました。

2019-01-19 10:13 UTC, Yoshitaka8419 commented on app/assets/javascripts/message.js
> +    .done(function(data){
拝承しました。修正しました。

2019-01-19 10:16 UTC, yuki-uchida approved these changes
LGTMです！

2019-01-19 10:21 UTC, merged