Chatspaceインクリメンタルサーチ実装
Yoshitaka8419/chat-space pull request #7
Opened 2019-01-21 08:17 UTC by Yoshitaka8419

# WHAT
**インクリメンタルサーチ実装**

# WHY
**インクリメンタルサーチは、リアルタイムで検索結果がわかり便利な機能**
**アプリ内での検索にはかかせない機能**

Gyozo⬇️のリンクです。
https://gyazo.com/4206ab1e1ffa172e40cb1faea2ed8a26

2019-01-21 08:22 UTC, takebn26 requested changes

2019-01-21 08:22 UTC, takebn26 commented on app/assets/javascripts/search.js
> +    var html = `<div class='chat-group-user clearfix js-chat-member' id='chat_group_user_22'>
idが元のままになっているので修正しましょう

2019-01-21 08:22 UTC, takebn26 commented on app/assets/javascripts/search.js
> +
意味的に分ける時に使う空行は基本一つで大丈夫です

2019-01-21 08:22 UTC, takebn26 commented
gifの中で文字が空白の時にすでに全てのユーザーが選択肢に出ているのが気になりますね

2019-01-21 09:47 UTC, Yoshitaka8419 commented on app/assets/javascripts/search.js
> +    var html = `<div class='chat-group-user clearfix js-chat-member' id='chat_group_user_22'>
詳細を教えていただけますか？

2019-01-21 09:51 UTC, takebn26 commented on app/assets/javascripts/search.js
> +    var html = `<div class='chat-group-user clearfix js-chat-member' id='chat_group_user_22'>
```
id="chat_group_user_22"
```
こちらの最初のダウンロードした時についているidだと思うのですが
idをそもそも使う必要がない場合は、削除してしまいましょう

2019-01-21 09:51 UTC, takebn26 commented
変更等の反映がなされていないようです
pushしましたか？

2019-01-22 07:25 UTC, Yoshitaka8419 commented on app/assets/javascripts/search.js
> +    var html = `<div class='chat-group-user clearfix js-chat-member' id='chat_group_user_22'>
拝承しました。

修正後Gyozo⬇️のリンクをもう一度送ります。
https://gyazo.com/cfc6c63b6876314e2527a38d3c611831

2019-01-22 07:25 UTC, Yoshitaka8419 commented on app/assets/javascripts/search.js
> +
拝承しました。

2019-01-22 07:33 UTC, ghost requested changes

2019-01-22 07:33 UTC, hiroki5123 commented on app/controllers/users_controller.rb
> +      format.html
ここの記述必要ないかと思います

2019-01-22 07:33 UTC, hiroki5123 commented on app/assets/javascripts/search.js
> +        // console.log(members)
削除しましょう

2019-01-22 07:51 UTC, Yoshitaka8419 commented on app/controllers/users_controller.rb
> +      format.html
修正しました。

2019-01-22 07:51 UTC, Yoshitaka8419 commented on app/assets/javascripts/search.js
> +        // console.log(members)
修正しました。

2019-01-22 07:56 UTC, ReoKuriyama commented
グループ編集時すでに加入しているユーザーを出力できていますか？

2019-01-25 06:03 UTC, miyagit commented on app/views/groups/_form.html.haml
> +        %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
form_forのヘルパーを使うようにしましょう。

2019-01-25 06:03 UTC, miyagit commented on app/views/groups/_form.html.haml
> +              %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove{ 'data-user-id': user.id } 削除
link_toを使いましょう。

2019-01-25 06:03 UTC, miyagit commented on app/views/groups/_form.html.haml
> +            %input{ type: "hidden", name: "group[user_ids][]", value: user.id }
form_forのヘルパーを使いましょう。

2019-01-25 06:03 UTC, miyagit commented on app/views/groups/_form.html.haml
> +        - @group.users.each do |user|
部分テンプレートを使いましょう。

2019-01-25 08:01 UTC, Yoshitaka8419 commented on app/views/groups/_form.html.haml
> +        %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
数人に聞いたところ、この箇所はform_forのヘルパーを使う必要はないのでは？とのことでした。
詳細おしえていただきますか？

2019-01-25 08:02 UTC, Yoshitaka8419 commented on app/views/groups/_form.html.haml
> +        - @group.users.each do |user|
すいませんコメントが理解できません。詳細おしえていただけますか？

2019-01-25 08:20 UTC, ShuheiTsuji commented on app/views/groups/_form.html.haml
> +        - @group.users.each do |user|
共通パーツや繰り返し処理をするパーツを部分テンプレートとして切り分けるという意味です。
pictweet mooovi を参考にしましょう。

2019-01-25 08:22 UTC, ShuheiTsuji commented on app/views/groups/_form.html.haml
> +        %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
form のヘルパーは、input に変換されるので、基本的に input で現在書かれたコードがあるのであれば、 form のヘルパーメソッドを使用すると変換可能です。

2019-01-26 05:36 UTC, Yoshitaka8419 commented on app/views/groups/_form.html.haml
> +        %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
```
<input class="chat-group-form__input js-user-search-field __web-inspector-hide-shortcut__" placeholder="追加したいユーザー名を入力してください" type="text">
```
完成されたチャットスペースのＨＴＭＬを確認したところ
name属性が宣言されていませんでした。
デモサイトでもただのinputで作成されているからなんじゃないですか？

https://thawing-stream-63240.herokuapp.com/groups/29342/edit

こちらになります。
もしform_helperでも記述が可能であれば
= f.text_field :name
の:nameの箇所をどの様に記述すればいいのか参考サイトなど教えていただけると幸いです。

2019-01-27 11:01 UTC, Yoshitaka8419 commented on app/views/groups/_form.html.haml
> +        - @group.users.each do |user|
部分テンプレートにしました。

2019-01-27 11:02 UTC, Yoshitaka8419 commented on app/views/groups/_form.html.haml
> +            %input{ type: "hidden", name: "group[user_ids][]", value: user.id }
form_forのヘルパーにしました。

2019-01-27 11:02 UTC, Yoshitaka8419 commented on app/views/groups/_form.html.haml
> +              %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove{ 'data-user-id': user.id } 削除
link_toを使いました。

2019-01-27 11:02 UTC, Yoshitaka8419 commented on app/views/groups/_form.html.haml
> +        %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
現地のメンターに聞いて解決済みです。

2019-01-27 11:06 UTC, ghost requested changes

2019-01-27 11:06 UTC, hiroki5123 commented on app/controllers/groups_controller.rb
> +    binding.pry
こちら削除お願いいたします 💦

2019-01-27 11:17 UTC, Yoshitaka8419 commented on app/controllers/groups_controller.rb
> +    binding.pry
削除いたしました！

2019-01-27 11:22 UTC, ghost approved these changes
LGTMです！

2019-01-27 11:24 UTC, merged