自動更新実装
Yoshitaka8419/chat-space pull request #8
Opened 2019-01-29 10:56 UTC by Yoshitaka8419

# WHAT
**chatspace自動更新実装機**

# WHY
**リアルタイムでchatのメッセージを閲覧できること**

2019-01-29 11:01 UTC, ghost requested changes

2019-01-29 11:01 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +        console.log(message_id)
削除しましょう

2019-01-29 11:01 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +        var html = buildHTML(message);
インデントがずれています

2019-01-29 11:14 UTC, Yoshitaka8419 commented on app/assets/javascripts/message.js
> +        console.log(message_id)
すいません。削除しました。

2019-01-29 11:14 UTC, Yoshitaka8419 commented on app/assets/javascripts/message.js
> +        var html = buildHTML(message);
インデント修正しました。

2019-01-29 11:17 UTC, yusukeyamane commented on app/assets/javascripts/message.js
> +        data.forEach(function(message){
ここは一段インデントを深くするべき箇所ですね

2019-01-29 11:17 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +        var html = buildHTML(message);
var html = buildHTML(message);
ここのインデントがずれていると指摘しています

2019-01-29 11:17 UTC, yusukeyamane commented on app/assets/javascripts/message.js
> +    } , 5000 );
カンマの後、にはスペースが必要ですが、前にはスペースは必要ありません

2019-01-29 11:17 UTC, yusukeyamane commented on app/assets/javascripts/message.js
> +      } else {
ifと同じ位置にインデントを正しましょう

2019-01-29 11:20 UTC, yusukeyamane commented on app/assets/javascripts/message.js
> +      if (location.href.match(/\/groups\/\d+\/messages/)){
if文までのインデントが深すぎますね

2019-01-30 03:31 UTC, Yoshitaka8419 commented on app/assets/javascripts/message.js
> +        var html = buildHTML(message);
気をつけます。
修正しました。

2019-01-30 03:31 UTC, Yoshitaka8419 commented on app/assets/javascripts/message.js
> +        data.forEach(function(message){
修正しました。

2019-01-30 03:31 UTC, Yoshitaka8419 commented on app/assets/javascripts/message.js
> +    } , 5000 );
修正しました。

2019-01-30 03:31 UTC, Yoshitaka8419 commented on app/assets/javascripts/message.js
> +      } else {
修正しました。

2019-01-30 03:31 UTC, Yoshitaka8419 commented on app/assets/javascripts/message.js
> +      if (location.href.match(/\/groups\/\d+\/messages/)){
修正しました。

2019-01-30 03:37 UTC, miyagit approved these changes
LGTMです。

2019-01-30 04:16 UTC, merged